### ISSUE TITLE
Problem processing block with path exception

### ISSUE THREAD

**Issue by mikedotmundy** [BEMADEV/HR-Management#29]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

We are seeing an exception hit every morning at 1:46 am which is just after our App Pool recycles. 

`(System.Exception) Problem processing block with path '~/Plugins/com_bemaservices/HrManagement/PtoAllocationDetail.ascx'.`

`(System.Web.HttpCompileException) C:\inetpub\wwwroot\Plugins\com_bemaservices\HrManagement\PtoAllocationDetail.ascx.cs(239): error CS0246: The type or namespace name 'PtoAllocationStatus' could not be found (are you missing a using directive or an assembly reference?)`

```
   at System.Web.Compilation.AssemblyBuilder.Compile()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)
   at Rock.Model.BlockTypeService.RegisterBlockTypes(String physWebAppPath, Boolean refreshAll) in \Rock\Model\CMS\BlockType\BlockTypeService.cs:line 564
```

### Expected Behavior

No exception.

### Actual Behavior

Exception logged when app pool restarts.

### Steps to Reproduce

Unsure - began after we updated the Plugin to v1.2.0.

### Rock Version

v19.3.4 (Beta)

### Plugin Version

v1.2.0

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
Fixed in https://github.com/BEMADEV/HR-Management/commit/db5b3e849de13243f18d63e4d03b7265340413de
